### ISSUE TITLE
wsgi 설정누락

### ISSUE THREAD

**Issue by leeceo97** [wanted-team-e/Humanscape#16]
https://github.com/wanted-team-e/Humanscape/blob/c6d26f3fe13f74f657d1befb0279deb8df35b76b/config/wsgi/develop.py#L14

**Comment by woodstock1993** [comment]
혹시 누락된 부분 추가하신 건가요? 서버 쪽에서 작업이 돼있는 것 같아서요.

**Comment by leeceo97** [comment]
@woodstock1993 os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.develop') 이렇게 변경부탁드려요! 아마 deploy브랜치에는 config.settings라고 되어있는데 저희가 settings.py를 분리 한곳으로 연결한걸 명시해줘야해서요

**Comment by woodstock1993** [comment]
이제 이해했습니다. 넵 알겠습니다.
