### ISSUE TITLE
이 부분 데이터베이스 분리부탁드려요

### ISSUE THREAD

**Issue by leeceo97** [wanted-team-e/Humanscape#17]
https://github.com/wanted-team-e/Humanscape/blob/c6d26f3fe13f74f657d1befb0279deb8df35b76b/config/settings/base.py#L93-L109

develop랑 deploy로 변경해서 각각옮겨주세요

**Comment by woodstock1993** [comment]
sqlite는 지우고 local db랑 원격 db 랑 동일한 potgres를  써서 로컬이랑 서버랑 .env 파일이 달라서 작동에는 문제가 없을 것 같아서  위에는 지우고 아래는 살리는 방향으로 진행했는데 괜찮을까요?

**Comment by leeceo97** [comment]
@woodstock1993 deploy랑 develop로 저정보 분리해서 옮겨달라고 전달드린거에요!

**Comment by woodstock1993** [comment]
넵 알겠습니다.
