### ISSUE TITLE
studies serializer fields

### ISSUE THREAD

**Issue by leeceo97** [wanted-team-e/Humanscape#7]
https://github.com/wanted-team-e/Humanscape/blob/2c91dc8102e5c42dcd0a7a6fec7d8a076f1819f8/studies/serializer.py#L7-L9

fields 부분 리스트말고 튜플 형태로 바꿔주시고 pep8맞춰서 변경 부탁드립니다

**Comment by kcw2297** [comment]
pep8과 데이터 형식 수정하겠습니다.

**Comment by kcw2297** [comment]
확인!
